# Generated by Django 5.0.6 on 2024-06-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=30, verbose_name='usuario')),
                ('password', models.TextField(verbose_name='senha')),
                ('email', models.TextField(verbose_name='email')),
            ],
        ),
    ]
